[package]
name = "blinkpay"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "blinkpay"

[dependencies]
anchor-lang = { version = "0.29.0" }
anchor-spl = "0.29.0"
thiserror = "1.0"
