version: "3.9"
services:
  backend:
    build:
      context: ../
      dockerfile: infra/Dockerfile.backend
    environment:
      - PORT=4000
      - SOLANA_RPC=https://api.devnet.solana.com
      - BLINKPAY_PROGRAM_ID=BLiNkPay11111111111111111111111111111111111
      - FRONTEND_BASE_URL=http://localhost:3000
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ../
      dockerfile: infra/Dockerfile.frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:4000
      - NEXT_PUBLIC_SOLANA_RPC=https://api.devnet.solana.com
    ports:
      - "3000:3000"
    depends_on:
      - backend
